- hosts: ansible1
  become: yes
  handlers:
    - name: restart services
      include_tasks: restart_services.yml

  tasks:
  - name:  Update sshd service and restart service
    ansible.builtin.template:
      src: sshd_config.j2
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: '0600'
      backup: yes
    notify: 
      - Restart sshd service
  
  - name: Update httpd service and restart service
    ansible.builtin.template:
      src: httpd_conf.j2
      dest: /etc/httpd.txt
      owner: root
      group: root
      mode: '0600'
      backup: yes
    notify: 
      - restart services
  
 
